[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xe5c07b"

# [colors.normal]
# black = "0x282c34"
# blue = "0x61afef"
# cyan = "0x56b6c2"
# green = "0x98c379"
# magenta = "0xc678dd"
# red = "0xe06c75"
# white = "0xdddddd"
# yellow = "0xe5c07b"


[colors.normal]
black = "0x1c1f26"  # Darker black
blue = "0x519ffb"   # Brighter blue
cyan = "0x42c7db"   # Brighter cyan
# green = "0xb8e183"  # Brighter green
green = "0x7cc449"
magenta = "0xdf7bff"  # Brighter magenta
red = "0xff5a6e"    # Brighter red
white = "0xdddddd"
yellow = "0xffd479" # Brighter yellow


[colors.primary]
background = "0x262626"
foreground  = "0xdddddd"


[font]
size = 13.0

[font.bold]
family = "Inconsolata"
# family = "Fira Code"
style = "Bold"

[font.italic]
family = "Inconsolata"
# family = "Fira Code"
style = "Italic"

[font.normal]
family = "Inconsolata"
# family = "Fira Code"
style = "Regular"

[font.offset]
x = 1
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"


[[keyboard.bindings]]
chars = "\u0003"
key = "D"
mods = "Control"


[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 3
y = 3

[window.position]
x = 0
y = 0
