#! /usr/bin/env bash

X="$@"
X=${X// /+}

url="https://www.google.de/search?q=$X"
echo "Opening $url"
if [[ "$(uname)" = "Darwin" ]]; then
    open -a "Firefox" "$url"
else
    firefox --new-tab "$url"
fi
